# Generated by Django 5.2 on 2025-10-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='city_images/')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration_in_years', models.CharField(max_length=20)),
                ('average_fees', models.DecimalField(decimal_places=2, help_text='Average fees in Lakhs (e.g., 5.50)', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='NIRF or other ranking', null=True)),
                ('fees_per_year', models.DecimalField(decimal_places=2, help_text='Fees in Lakhs (e.g., 2.2)', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='college_images/')),
                ('area', models.CharField(blank=True, help_text="e.g., 'South Delhi'", max_length=150, null=True)),
                ('college_type', models.CharField(choices=[('GOVT', 'Government'), ('PVT', 'Private'), ('SEMI', 'Semi-Government')], default='PVT', max_length=4)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='colleges.city')),
                ('courses', models.ManyToManyField(related_name='colleges', to='colleges.course')),
            ],
        ),
    ]
