# Generated by Django 5.2 on 2025-10-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the college', null=True),
        ),
    ]
