# Generated by Django 5.2 on 2025-10-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='rank_source',
            field=models.CharField(blank=True, help_text='e.g., NIRF, India Today, Outlook', max_length=100, null=True),
        ),
    ]
